version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        expose:
            - "3306"
        environment:
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - mysql:/var/lib/mysql/
        networks:
            - app-network
    
    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./etc/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8881:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql: